export class ApiError extends Error {
  constructor(public code: string, public override message: string) {
    super(message);
    this.name = "ApiError";
  }
}
export const ERROR = {
  // ── 공통 ──
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  CONFLICT: "CONFLICT",
  // ── A파트 (인증/계정) ──
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  ACCOUNT_WITHDRAWN: "ACCOUNT_WITHDRAWN",
  NICKNAME_ALREADY_EXISTS: "NICKNAME_ALREADY_EXISTS",
  // ── B파트 (추천/호감) ──
  ALREADY_SELECTED: "ALREADY_SELECTED",
  INVALID_ITEM: "INVALID_ITEM",
  DUPLICATE_INTEREST: "DUPLICATE_INTEREST",
  REC_NOT_GENERATED: "REC_NOT_GENERATED",
  INVALID_INTEREST: "INVALID_INTEREST",
  ALREADY_PROCESSED: "ALREADY_PROCESSED",
  ALREADY_PASSED: "ALREADY_PASSED",
  INVALID_INPUT: "INVALID_INPUT",
  // ── C파트 (채팅) ──
  INVALID_SOURCE: "INVALID_SOURCE",
  DUPLICATE_ACTIVE_ROOM: "DUPLICATE_ACTIVE_ROOM",
  REMATCH_TOO_SOON: "REMATCH_TOO_SOON",
  ROOM_EXPIRED: "ROOM_EXPIRED",
  ROOM_NOT_ACTIVE: "ROOM_NOT_ACTIVE",
  // ── D파트 (피드) ──
  INVALID_FEED_ID: "INVALID_FEED_ID",
  FEED_NOT_FOUND: "FEED_NOT_FOUND",
  FEED_NOT_ACTIVE: "FEED_NOT_ACTIVE",
  FEED_NOT_AVAILABLE: "FEED_NOT_AVAILABLE",
  FEED_ALREADY_ACTIVE: "FEED_ALREADY_ACTIVE",
  FEED_ALREADY_DELETED: "FEED_ALREADY_DELETED",
  FEED_NOT_OWNER: "FEED_NOT_OWNER",
  NO_UPDATE_FIELDS: "NO_UPDATE_FIELDS",
  INVALID_TEXT: "INVALID_TEXT",
  INVALID_KEYWORDS: "INVALID_KEYWORDS",
  INVALID_KEYWORD_ID: "INVALID_KEYWORD_ID",
  INVALID_CURSOR: "INVALID_CURSOR",
  // ── D파트 (댓글) ──
  INVALID_CONTENT: "INVALID_CONTENT",
  INVALID_COMMENT_ID: "INVALID_COMMENT_ID",
  CANNOT_COMMENT_OWN_FEED: "CANNOT_COMMENT_OWN_FEED",
  COMMENT_ALREADY_EXISTS: "COMMENT_ALREADY_EXISTS",
  COMMENT_NOT_FOUND: "COMMENT_NOT_FOUND",
  COMMENT_DELETED: "COMMENT_DELETED",
  NOT_FEED_AUTHOR: "NOT_FEED_AUTHOR",
  COMMENTER_BANNED: "COMMENTER_BANNED",
  BLOCKED_RELATIONSHIP: "BLOCKED_RELATIONSHIP",
  CHAT_ROOM_ALREADY_EXISTS: "CHAT_ROOM_ALREADY_EXISTS",
  // ── D파트 (차단) ──
  INVALID_BLOCKED_USER_ID: "INVALID_BLOCKED_USER_ID",
  INVALID_REASON: "INVALID_REASON",
  CANNOT_BLOCK_SELF: "CANNOT_BLOCK_SELF",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  ALREADY_BLOCKED: "ALREADY_BLOCKED",
  INVALID_BLOCK_ID: "INVALID_BLOCK_ID",
  BLOCK_NOT_FOUND: "BLOCK_NOT_FOUND",
  BLOCK_NOT_OWNER: "BLOCK_NOT_OWNER",
  ALREADY_UNBLOCKED: "ALREADY_UNBLOCKED",
  // ── D파트 (전화번호 차단) ──
  INVALID_PHONE_NUMBER: "INVALID_PHONE_NUMBER",
  INVALID_PHONE_FORMAT: "INVALID_PHONE_FORMAT",
  // ── D파트 (신고) ──
  INVALID_TARGET_TYPE: "INVALID_TARGET_TYPE",
  INVALID_TARGET_ID: "INVALID_TARGET_ID",
  INVALID_REASON_TYPE: "INVALID_REASON_TYPE",
  INVALID_DESCRIPTION: "INVALID_DESCRIPTION",
  TARGET_NOT_FOUND: "TARGET_NOT_FOUND",
  CANNOT_REPORT_SELF: "CANNOT_REPORT_SELF",
} as const;
export type ErrorCode = (typeof ERROR)[keyof typeof ERROR];