export const ERROR = {
  // ── 공통 ──
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  // ── C파트 (채팅) ──
  BLOCKED_RELATION: "BLOCKED_RELATION",
  ROOM_EXPIRED: "ROOM_EXPIRED",
  ROOM_NOT_ACTIVE: "ROOM_NOT_ACTIVE",
  DUPLICATE_ACTIVE_ROOM: "DUPLICATE_ACTIVE_ROOM",
  REMATCH_TOO_SOON: "REMATCH_TOO_SOON",
  INVALID_SOURCE: "INVALID_SOURCE",

  // ── D파트 (피드) ──
  INVALID_FEED_ID: "INVALID_FEED_ID",
  FEED_NOT_FOUND: "FEED_NOT_FOUND",
  FEED_NOT_ACTIVE: "FEED_NOT_ACTIVE",
  FEED_NOT_AVAILABLE: "FEED_NOT_AVAILABLE",
  FEED_ALREADY_ACTIVE: "FEED_ALREADY_ACTIVE",
  FEED_NOT_OWNER: "FEED_NOT_OWNER",
  NO_UPDATE_FIELDS: "NO_UPDATE_FIELDS",
  INVALID_TEXT: "INVALID_TEXT",
  INVALID_KEYWORDS: "INVALID_KEYWORDS",
  INVALID_KEYWORD_ID: "INVALID_KEYWORD_ID",
  INVALID_CURSOR: "INVALID_CURSOR",

  // ── D파트 (댓글) ──
  INVALID_CONTENT: "INVALID_CONTENT",
  INVALID_COMMENT_ID: "INVALID_COMMENT_ID",
  CANNOT_COMMENT_OWN_FEED: "CANNOT_COMMENT_OWN_FEED",
  COMMENT_ALREADY_EXISTS: "COMMENT_ALREADY_EXISTS",
  COMMENT_NOT_FOUND: "COMMENT_NOT_FOUND",
  COMMENT_DELETED: "COMMENT_DELETED",
  NOT_FEED_AUTHOR: "NOT_FEED_AUTHOR",
  COMMENTER_BANNED: "COMMENTER_BANNED",
  BLOCKED_RELATIONSHIP: "BLOCKED_RELATIONSHIP",
  CHAT_ROOM_ALREADY_EXISTS: "CHAT_ROOM_ALREADY_EXISTS",

  // ── D파트 (차단) ──
  INVALID_BLOCKED_USER_ID: "INVALID_BLOCKED_USER_ID",
  INVALID_REASON: "INVALID_REASON",
  CANNOT_BLOCK_SELF: "CANNOT_BLOCK_SELF",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  ALREADY_BLOCKED: "ALREADY_BLOCKED",

  // ── D파트 (전화번호 차단) ──
  INVALID_PHONE_NUMBER: "INVALID_PHONE_NUMBER",
  INVALID_PHONE_FORMAT: "INVALID_PHONE_FORMAT",

  // ── D파트 (신고) ──
  INVALID_TARGET_TYPE: "INVALID_TARGET_TYPE",
  INVALID_TARGET_ID: "INVALID_TARGET_ID",
  INVALID_REASON_TYPE: "INVALID_REASON_TYPE",
  INVALID_DESCRIPTION: "INVALID_DESCRIPTION",
  TARGET_NOT_FOUND: "TARGET_NOT_FOUND",
  CANNOT_REPORT_SELF: "CANNOT_REPORT_SELF",
} as const;

export type ErrorCode = (typeof ERROR)[keyof typeof ERROR];
